feat(platform): Platform Telemetry
proofzero/rollupid pull request #2459
Opened 2023-07-04 23:39 UTC by poolsar42

### Description

Sets up PostHog for Analytics

### Related Issues

- Closes #2444

### Testing

TBD

### Checklist

- [x] I have read the [CONTRIBUTING](CONTRIBUTING.md) guidelines
- [x] I have tested my code (manually and/or automated if applicable)
- [ ] I have updated the documentation (if necessary)

2023-07-05 05:14 UTC, szkl requested changes

2023-07-05 05:14 UTC, szkl commented on apps/console/.dev.vars.example
> +REACT_APP_PUBLIC_POSTHOG_KEY=""
`POSTHOG_PUBLIC_KEY`

2023-07-05 05:14 UTC, szkl commented on apps/console/.dev.vars.example
> +REACT_APP_PUBLIC_POSTHOG_HOST=""
`POSTHOG_HOST`

2023-07-06 20:22 UTC, szkl requested changes
Define new environment variables in GitHub workflow configuration files.

Is it possible to match `platform/posthog/tsconfig.json` with others?

2023-07-06 20:22 UTC, szkl commented on apps/console/app/entry.server.tsx
> +            '*.workers.dev',
Is it possible to restrict the subdomain to some?

2023-07-06 20:22 UTC, szkl commented on apps/console/app/routes/apps/$clientId/auth.tsx
> +                  }
Prefer early returns to avoid indentations.

2023-07-06 20:22 UTC, szkl commented on apps/console/app/routes/apps/new.tsx
> +                      }}
```suggestion
                      onClick={() => posthog?.capture('new_app_created')}
```

2023-07-06 20:22 UTC, szkl commented on apps/passport/app/components/Header/index.tsx
> +                      }}
```suggestion
                      onClick={() => posthog.reset()}
```

2023-07-06 20:22 UTC, szkl commented on platform/address/src/jsonrpc/methods/resolveAccount.ts
> +
Define this as a generic utility function.

2023-07-06 20:22 UTC, szkl commented on platform/posthog/package.json
> +    "@cloudflare/workers-types": "^4.20230419.0",
`npm config set save-exact true`

2023-07-06 20:22 UTC, szkl commented on platform/posthog/src/index.ts
> +  response.headers.set('Access-Control-Allow-Credentials', 'true')
Defina a package local utility function.

2023-07-06 20:22 UTC, szkl commented on platform/posthog/wrangler.toml
> +]
Redundant.

2023-07-06 22:56 UTC, szkl requested changes

2023-07-06 22:56 UTC, szkl commented on .github/workflows/main-address.yaml
> +          POSTHOG_API_KEY: ${{secrets.POSTHOG_API_KEY_DEV }}
```suggestion
          POSTHOG_API_KEY: ${{ secrets.POSTHOG_API_KEY_DEV }}
```

2023-07-06 22:56 UTC, szkl commented on apps/passport/app/root.tsx
> +import posthog from 'posthog-js'
```suggestion
import posthog from 'posthog-js'
import { PostHogProvider } from 'posthog-js/react'
```

I find this easier for readability.

2023-07-06 22:56 UTC, szkl commented on packages/utils/posthog.ts
> +  await fetch(`${POSTHOG_PROXY_HOST}/e/`, init)
It is a good idea to just return here instead. Let the caller decide.

2023-07-06 22:56 UTC, szkl commented on platform/posthog/package.json
> +    "typescript": "^5.0.4",
```suggestion
    "typescript": "5.0.4",
```

2023-07-06 22:56 UTC, szkl commented on platform/posthog/package.json
> +    "wrangler": "^3.0.0"
```suggestion
    "wrangler": "3.0.0"
```

2023-07-06 22:56 UTC, szkl commented on platform/posthog/package.json
> +    "wrangler": "^3.0.0"
I think this is not the latest.

2023-07-06 22:56 UTC, szkl commented on platform/posthog/wrangler.toml
> +[dev]
If it is possible to use this worker on `dev`, `next`, and `current` environments then I think this environment can be just called `main` or something like that.

2023-07-06 22:56 UTC, szkl commented on packages/utils/posthog.ts
> +  apiKey: string
Is this the only parameter representing the environment?

2023-07-06 23:02 UTC, poolsar42 commented on packages/utils/posthog.ts
> +  apiKey: string
Yeah, only one API key per app in PostHog

Our proxy worker sends requests with specific API key and then it gets sorted in posthog

2023-07-06 23:15 UTC, szkl approved these changes

2023-07-07 14:56 UTC, merged